# ##################################
# About GitHub Pages and Jekyll
# https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/about-github-pages-and-jekyll
# Adding a theme to your GitHub Pages site using Jekyll
# https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/adding-a-theme-to-your-github-pages-site-using-jekyll
# ##################################
# Github Pages supported themes: Architect, Cayman, Dinky, Hacker, Leap day, 
# Merlot, Midnight, Minima, Minimal, Modernist, Slate, Tactile, Time machine
# source @ https://github.com/pages-themes/{theme-name}
# list @ https://pages.github.com/themes/
# repos @ https://github.com/orgs/pages-themes/repositories
# theme topic @ https://github.com/topics/jekyll-theme
# ##################################
# initial
# theme: jekyll-theme-midnight
# theme: minima 
# remote_theme: THEME-NAME
# ##################################
# https://just-the-docs.github.io/just-the-docs/#getting-started 
# https://github.com/just-the-docs/just-the-docs
# https://github.com/just-the-docs/just-the-docs-template/blob/main/README.md
# https://jekyllthemes.io/theme/just-the-docs
title: Dev Docs
description: Illegitimis' dev documentation, tutorial, memory pointers, inverse oblivion
# theme: just-the-docs
remote_theme: just-the-docs/just-the-docs
url: https://illegitimis.github.io/Tutorial/

# https://github.com/just-the-docs/just-the-docs/blob/main/_config.yml
permalink: pretty
defaults:
  - scope:
      path: "doc" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"
search_enabled: true
search:
  # Supports 1 - 6, default: 2
  heading_level: 3
  # Maximum amount of previews per search result; Default: 3
  previews: 2
  # Maximum amount of words to display before a matched word in the preview; Default: 5
  preview_words_before: 3
  # Maximum amount of words to display after a matched word in the preview; Default: 10
  preview_words_after: 3
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results; Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: true
  # Focus the search input by pressing `ctrl + focus_shortcut_key` (or `cmd + focus_shortcut_key` on macOS)
  focus_shortcut_key: "k"

# For copy button on code
enable_copy_code_button: true

# Enable or disable heading anchors
heading_anchors: true

# Enable or disable the side/mobile menu globally
# Nav menu can also be selectively enabled or disabled using page variables or the minimal layout
nav_enabled: true

# Sort order for navigation links
# nav_sort: case_insensitive # default, equivalent to nil
nav_sort: case_sensitive # Capital letters sorted before lowercase

# Show navigation error report
nav_error_report: true # default is false/nil.

liquid:
  error_mode: strict
  strict_filters: true

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"


footer_content: 'Using just-the-docs theme with <a href="https://github.com/just-the-docs/just-the-docs/tree/main/LICENSE.txt">MIT license.</a>'

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# Color scheme currently only supports "dark", "light"/nil (default), or a custom scheme that you define
color_scheme: dark

callouts_level: quiet # or loud
callouts:
  highlight:
    color: red
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: yellow

# Google Analytics Tracking (optional)
# Supports a CSV of tracking ID strings (eg. "UA-1234567-89,G-1AB234CDE5")
# Note: the main Just the Docs site does *not* use Google Analytics.
# ga_tracking: UA-2709176-10,G-5FG1HLH3XQ
# ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true/nil by default)

plugins:
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-include-cache
  - jekyll-sitemap

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false
  # ignore:
  #   envs: all


